### ISSUE TITLE
проблемы с локализацией

### ISSUE THREAD

**Issue by Pro-pra** [pfs-utils/pfs-utils#8]
посмотрите файл unload_pfs строки 55, 58 и 67
В них используется двойная переменная, gettext ее не может обработать.
Надо вынести значение basename ${filemnt} в переменную.

НО почему-то у меня это не получается :( задаю: name="$(basename ${filemnt}")"
прошу поправить скрит

**Comment by ZayK** [comment]
Не изучал gettext, но по идее переменные ему передавать не надо.
Надо бы посмотреть примеры правильного использования gettext.

Может что-то вроде   "$(gettext ' Файл ')\"$(basename "${filemnt}")\"$(gettext ' отключен. ')\n"   ?

name="$(basename ${filemnt}")" - ошибка с кавычками, но дело не в ней, как я понял?

**Comment by Pro-pra** [comment]
Ну легче передавать с переменной фразу целиком, и если одна переменная передается то все нормально вроде, в нашем случае проблема в том что переменная "вложенная" т.е. ${filemnt} вложено в другую переменную. gettext такое не может обработать совсем, поэтому в данном файле предлагаю вынести "$(basename ${filemnt}")" в переменную и ее прописать в строках.

**Comment by Pro-pra** [comment]
закоммитил решение.
буду откатывать кавычки т.к. eval_gettext почему-то не хочет с ними

**Comment by ZayK** [comment]
Убирать названия пакетов из диалогов - не желательно.
Некоторые, например, могут очень долго обрабатываться, и когда выскакивает окно "Не удалось ..." без имени пакета - не ясно, о каком пакете речь.
